# For tesing on one windows machine
version: "3.9"

services:
  node1:
    build: .
    container_name: node1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_PATH: ${DATA_PATH}
      NODE_ROLE: ${NODE_ROLE}
      WORKER_ID: "node1"
      PORT: 8001
      MODE: "auto"
      PEERS: "node1:8001,node2:8002,node3:8003"
      BATCH: 128
      # override on Linux host: OLLAMA_URL=http://192.168.x.y:11434
      OLLAMA_URL: "http://host.docker.internal:11434"
    command: ["python","-u","/app/app/node.py","--csv","/data/questions.csv","--port","8001","--mode","auto","--prefer-leader"]
    ports:
      - "8001:8001"
    volumes:
      - ./data:/data:ro
      - ./output:/output
      - ./replicated:/replicated
      - ./state:/state

  node2:
    build: .
    container_name: node2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_PATH: ${DATA_PATH}
      NODE_ROLE: ${NODE_ROLE}
      WORKER_ID: "node2"
      PORT: 8002
      MODE: "auto"
      PEERS: "node1:8001,node2:8002,node3:8003"
      BATCH: 128
      OLLAMA_URL: "http://host.docker.internal:11434"
    command: ["python","-u","/app/app/node.py","--csv","/data/questions.csv","--port","8002","--mode","auto"]
    ports:
      - "8002:8002"
    volumes:
      - ./data:/data:ro
      - ./output:/output
      - ./replicated:/replicated
      - ./state:/state

  node3:
    build: .
    container_name: node3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_PATH: ${DATA_PATH}
      NODE_ROLE: ${NODE_ROLE}
      WORKER_ID: "node3"
      PORT: 8003
      MODE: "auto"
      PEERS: "node1:8001,node2:8002,node3:8003"
      BATCH: 128
      OLLAMA_URL: "http://host.docker.internal:11434"
    command: ["python","-u","/app/app/node.py","--csv","/data/questions.csv","--port","8003","--mode","auto"]
    ports:
      - "8003:8003"
    volumes:
      - ./data:/data:ro
      - ./output:/output
      - ./replicated:/replicated
      - ./state:/state

# For production on linux, only one node (ip adresses of other nodes needed)

# version: "3.9"

# services:
#   node:
#     image: bert-classifier-node:latest   # or build: .
#     container_name: node
#     restart: unless-stopped
#     env_file:
#       - .env
#     network_mode: host                   # <- Linux-only; shares host network
#     environment:
#       WORKER_ID: ${WORKER_ID}
#       PORT: ${PORT}
#       PREFER_LEADER: ${PREFER_LEADER:-false}
#       MODE: "auto"
#       PEERS: "${PEERS}"                  # comma-separated LAN_IP:PORT of all nodes
#       CSV: "/data/questions.csv"
#       OLLAMA_URL: "http://127.0.0.1:11434"  # host & container share network
#     command: ["python","-u","/app/app/node.py","--csv","/data/questions.csv","--port","${PORT:-8001}","--mode","auto","--prefer-leader"]
#     volumes:
#       - ./data:/data:ro
#       - ./output:/output
#       - ./replicated:/replicated
#       - ./state:/state

