name: Deploy Portfolio (static HTML)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Publish ONLY the Portfolio/ folder as the site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "Portfolio"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
